export enum AssignmentStatus {
  PENDING_OFFER = 'PENDING_OFFER',
  OFFERED = 'OFFERED',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
  REASSIGNED = 'REASSIGNED',
}
