export enum DeliveryStatus {
  DRAFT = 'DRAFT',
  QUOTED = 'QUOTED',
  CONFIRMED = 'CONFIRMED',
  SEARCHING_RIDER = 'SEARCHING_RIDER',
  RIDER_ASSIGNED = 'RIDER_ASSIGNED',
  EN_ROUTE_PICKUP = 'EN_ROUTE_PICKUP',
  ARRIVED_PICKUP = 'ARRIVED_PICKUP',
  PICKED_UP = 'PICKED_UP',
  EN_ROUTE_DROP = 'EN_ROUTE_DROP',
  ARRIVED_DROP = 'ARRIVED_DROP',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  FAILED = 'FAILED',
  RETURN_REQUIRED = 'RETURN_REQUIRED',
  RETURNED = 'RETURNED',
  DISPUTED = 'DISPUTED',
}

export const TERMINAL_DELIVERY_STATUSES = new Set<DeliveryStatus>([
  DeliveryStatus.DELIVERED,
  DeliveryStatus.CANCELLED,
  DeliveryStatus.FAILED,
  DeliveryStatus.RETURNED,
]);
